[2022-09-02 12:19:12,834] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Load scheduled__2022-08-28T00:20:00+00:00 [queued]>
[2022-09-02 12:19:12,837] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Load scheduled__2022-08-28T00:20:00+00:00 [queued]>
[2022-09-02 12:19:12,837] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:19:12,837] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-02 12:19:12,837] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:19:12,841] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Load> on 2022-08-28 00:20:00+00:00
[2022-09-02 12:19:12,847] {standard_task_runner.py:52} INFO - Started process 36502 to run task
[2022-09-02 12:19:12,852] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_crime', 'Load', 'scheduled__2022-08-28T00:20:00+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/etl_bigquery.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpxsvq5wiz', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmp3g6vr874']
[2022-09-02 12:19:12,853] {standard_task_runner.py:77} INFO - Job 542: Subtask Load
[2022-09-02 12:19:12,877] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_crime.Load scheduled__2022-08-28T00:20:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-02 12:19:12,899] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_crime
AIRFLOW_CTX_TASK_ID=Load
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T00:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-28T00:20:00+00:00
[2022-09-02 12:19:16,113] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2022-09-02 12:19:19,117] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2022-09-02 12:19:19,119] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:19:19,120] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-02 12:19:20,691] {logging_mixin.py:109} WARNING - Downloading:   0%|          | 0/200 [00:00<?, ?rows/s]
[2022-09-02 12:19:20,945] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 787.68rows/s]
[2022-09-02 12:19:20,946] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 785.37rows/s]
[2022-09-02 12:19:20,946] {logging_mixin.py:109} WARNING - 
[2022-09-02 12:19:25,570] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-02 12:19:25,572] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-02 12:19:25,574] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 914.99it/s]
[2022-09-02 12:19:25,575] {logging_mixin.py:109} WARNING - 
[2022-09-02 12:19:25,575] {logging_mixin.py:109} INFO - Done, please check the table
[2022-09-02 12:19:25,576] {python.py:175} INFO - Done. Returned value was: None
[2022-09-02 12:19:25,589] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_crime, task_id=Load, execution_date=20220828T002000, start_date=20220902T171912, end_date=20220902T171925
[2022-09-02 12:19:25,628] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-02 12:19:25,636] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
